// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timesheet_app.Data;

#nullable disable

namespace Timesheet_app.Migrations
{
    [DbContext(typeof(SQLServerDBConnection))]
    [Migration("20260626133418_AddTimesheetTemplate")]
    partial class AddTimesheetTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Timesheet_app.Models.CompanyModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Timesheet_app.Models.HollidayModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<bool>("Recurring")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("Timesheet_app.Models.ProjectDetailModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectDetails");
                });

            modelBuilder.Entity("Timesheet_app.Models.ProjectModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Timesheet_app.Models.TimesheetModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("AccumulatedTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ClockIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ClockOut")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("TaskDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WFO")
                        .HasColumnType("int");

                    b.Property<bool>("Working")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("Timesheet_app.Models.TimesheetTemplateHeaderModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimesheetTemplateModelId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetTemplateModelId");

                    b.ToTable("TimesheetTemplateHeaders");
                });

            modelBuilder.Entity("Timesheet_app.Models.TimesheetTemplateModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseTemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyModelId");

                    b.ToTable("TimesheetTemplates");
                });

            modelBuilder.Entity("Timesheet_app.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSpk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyModelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Timesheet_app.Models.UserProjectModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("Timesheet_app.Models.ProjectDetailModel", b =>
                {
                    b.HasOne("Timesheet_app.Models.ProjectModel", "Project")
                        .WithMany("Details")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Timesheet_app.Models.TimesheetModel", b =>
                {
                    b.HasOne("Timesheet_app.Models.UserModel", "User")
                        .WithMany("Timesheets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Timesheet_app.Models.TimesheetTemplateHeaderModel", b =>
                {
                    b.HasOne("Timesheet_app.Models.TimesheetTemplateModel", null)
                        .WithMany("Header")
                        .HasForeignKey("TimesheetTemplateModelId");
                });

            modelBuilder.Entity("Timesheet_app.Models.TimesheetTemplateModel", b =>
                {
                    b.HasOne("Timesheet_app.Models.CompanyModel", null)
                        .WithMany("TimesheetTemplates")
                        .HasForeignKey("CompanyModelId");
                });

            modelBuilder.Entity("Timesheet_app.Models.UserModel", b =>
                {
                    b.HasOne("Timesheet_app.Models.CompanyModel", null)
                        .WithMany("Users")
                        .HasForeignKey("CompanyModelId");
                });

            modelBuilder.Entity("Timesheet_app.Models.UserProjectModel", b =>
                {
                    b.HasOne("Timesheet_app.Models.ProjectModel", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timesheet_app.Models.UserModel", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Timesheet_app.Models.CompanyModel", b =>
                {
                    b.Navigation("TimesheetTemplates");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Timesheet_app.Models.ProjectModel", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("Timesheet_app.Models.TimesheetTemplateModel", b =>
                {
                    b.Navigation("Header");
                });

            modelBuilder.Entity("Timesheet_app.Models.UserModel", b =>
                {
                    b.Navigation("Timesheets");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
