using Microsoft.EntityFrameworkCore;
using Timesheet_app.Models;
using Timesheet_app.Models.DTOs;
using Timesheet_app.Repositories;

namespace Timesheet_app.Services
{
    public class HollidayService : IHollidayService
    {
        private readonly IHollidayRepo _hollidayRepo;

        public HollidayService(IHollidayRepo hollidayRepo)
        {
            _hollidayRepo = hollidayRepo;
        }
        public Task AddHoliday(HollidayDTO holiday)
        {
            var hollidayModel = ChangeDTOToToModel(holiday);
                hollidayModel.Id = IdGenerated(hollidayModel);
            return _hollidayRepo.AddHolliday(hollidayModel);
        }

        public async Task<List<HollidayDTO>> GenerateRecuringHoliday(int year)
        {
            var listOfRecuring = await _hollidayRepo.GetRecuringHoliday();
            var newListOfRecuring = new List<HollidayDTO>();

            foreach(var holliday in listOfRecuring)
            {
                var newHolliday = new HollidayModel()
                {
                    Id = null,
                    Day = holliday.Day,
                    Month = holliday.Month,
                    Year = year,
                    Recurring = holliday.Recurring,
                    Description = holliday.Description
                };
                newHolliday.Id = IdGenerated(newHolliday);
                await _hollidayRepo.AddHolliday(newHolliday);
                newListOfRecuring.Add(ChangeModelToDTO(newHolliday));
            }
            return newListOfRecuring;
        }

        public async Task<HollidayDTO?> GetHolidayByDate(DateOnly date)
        {
            var day = date.Day;
            var month = date.Month;
            var year = date.Year;
            var yearNow = DateTime.Now.Year;
            if (day == 0 || month == 0 || month > 12 || year == 0 || year > yearNow)
            {
                throw new ArgumentException($"Invalid date '{date}'");
            }

            else if (day == null || month == null || year == null)
            {
                throw new ArgumentException($"Invalid date '{date}'. Day, month, and year cannot be null.");
            }
            else
            {
                var holliday = await _hollidayRepo.GetHollidayByDateAsync(day, month, year);
                if (holliday == null)
                {
                    return null;
                }
                var hollidayDto = ChangeModelToDTO(holliday);

                return hollidayDto;
            }
        }

        private static HollidayModel ChangeDTOToToModel(HollidayDTO hollidayDTO)
        {

            return new HollidayModel()
            {
                Id = null, // Id will be generated by the database or repository layer
                Day = hollidayDTO.Day,
                Month = hollidayDTO.Month,
                Year = hollidayDTO.Year,
                Recurring = hollidayDTO.Recurring,
                Description = hollidayDTO.Description

            };
        }

        private static HollidayDTO ChangeModelToDTO(HollidayModel hollidayModel)
        {
            return new HollidayDTO()
            {
                Day = hollidayModel.Day,
                Month = hollidayModel.Month,
                Year = hollidayModel.Year,
                Recurring = hollidayModel.Recurring,
                Description = hollidayModel.Description
            };

        }

        private static string IdGenerated(HollidayModel hollidayModel)
        {
            var hollidayDate = new DateOnly(hollidayModel.Year, hollidayModel.Month, hollidayModel.Day);
            var isItRecuring = hollidayModel.Recurring ? "R" : "N";
            return $"HOL-{hollidayDate.ToString("yyyyMMdd")}-{isItRecuring}";
        }
    }
}
